dist: xenial

services:
  - postgresql

addons:
  chrome: stable

language: python

python:
  - "3.7"

before_install:
  - psql -c 'create database test_db;' -U postgres
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - pip install -r requirements.txt
  - wget -N https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

before_script:
  - python ./twa_app/manage.py db upgrade
  - sudo touch output_file
  - sudo chmod 777 output_file

script:
  - bash runtests.sh

notifications:
    email: false